rhel10 build fix
To build on RHEL 10, using system zlib-ng must currently be disabled (or the error patched out)

Error message on RHEL 10 build:

[13653/22150] /usr/bin/g++ -MD -MF obj/third_party/zlib/google/zip/zip_internal.o.d -DUSE_UDEV -DUSE_AURA=1 -DUSE_OZONE=1 -DOFFICIAL_BUILD -DTOOLKIT_QT -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DNO_UNWIND_TABLES -D_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_NONE -D_GLIBCXX_ASSERTIONS=1 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DUSING_SYSTEM_ICU=1 -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_STATIC -Igen -I../../../../../src/3rdparty/chromium -I../../../../../src/3rdparty/chromium/third_party/perfetto/include -Igen/third_party/perfetto/build_config -Igen/third_party/perfetto -I../../../../../src/3rdparty/chromium/base/allocator/partition_allocator/src -Igen/base/allocator/partition_allocator/src -I../../../../../src/3rdparty/chromium/third_party/abseil-cpp -I../../../../../src/3rdparty/chromium/third_party/boringssl/src/include -I../../../../../src/3rdparty/chromium/third_party/protobuf/src -Igen/protoc_out -I../../../../../src/3rdparty/chromium/third_party/ced/src -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -Wno-unused-local-typedefs -Wno-maybe-uninitialized -Wno-deprecated-declarations -fno-delete-null-pointer-checks -Wno-comments -Wno-packed-not-aligned -Wno-misleading-indentation -Wno-dangling-else -Wno-missing-field-initializers -Wno-unused-parameter -Wno-psabi -fno-ident -fno-strict-aliasing -fstack-protector -Wno-unknown-pragmas -Wno-address -Wno-parentheses -Wno-sign-compare -Wno-stringop-overflow -Wno-stringop-overread -Wno-psabi -Wno-multichar -Wno-format-zero-length -fno-unwind-tables -fno-asynchronous-unwind-tables -fPIC -pipe -pthread -m64 -msse3 -O2 -fdata-sections -ffunction-sections -fno-math-errno -fno-omit-frame-pointer -gdwarf-4 -g1 -fvisibility=hidden -Wno-narrowing -Wno-class-memaccess -Wno-attributes -Wno-class-memaccess -Wno-subobject-linkage -Wno-invalid-offsetof -Wno-return-type -Wno-deprecated-copy -Wno-invalid-offsetof -Wno-deprecated-copy -Wno-expansion-to-defined -std=gnu++20 -fno-exceptions -fno-rtti -fvisibility-inlines-hidden -c ../../../../../src/3rdparty/chromium/third_party/zlib/google/zip_internal.cc -o obj/third_party/zlib/google/zip/zip_internal.o
FAILED: obj/third_party/zlib/google/zip/zip_internal.o 
/usr/bin/g++ -MD -MF obj/third_party/zlib/google/zip/zip_internal.o.d -DUSE_UDEV -DUSE_AURA=1 -DUSE_OZONE=1 -DOFFICIAL_BUILD -DTOOLKIT_QT -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DNO_UNWIND_TABLES -D_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_NONE -D_GLIBCXX_ASSERTIONS=1 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DUSING_SYSTEM_ICU=1 -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_STATIC -Igen -I../../../../../src/3rdparty/chromium -I../../../../../src/3rdparty/chromium/third_party/perfetto/include -Igen/third_party/perfetto/build_config -Igen/third_party/perfetto -I../../../../../src/3rdparty/chromium/base/allocator/partition_allocator/src -Igen/base/allocator/partition_allocator/src -I../../../../../src/3rdparty/chromium/third_party/abseil-cpp -I../../../../../src/3rdparty/chromium/third_party/boringssl/src/include -I../../../../../src/3rdparty/chromium/third_party/protobuf/src -Igen/protoc_out -I../../../../../src/3rdparty/chromium/third_party/ced/src -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -Wno-unused-local-typedefs -Wno-maybe-uninitialized -Wno-deprecated-declarations -fno-delete-null-pointer-checks -Wno-comments -Wno-packed-not-aligned -Wno-misleading-indentation -Wno-dangling-else -Wno-missing-field-initializers -Wno-unused-parameter -Wno-psabi -fno-ident -fno-strict-aliasing -fstack-protector -Wno-unknown-pragmas -Wno-address -Wno-parentheses -Wno-sign-compare -Wno-stringop-overflow -Wno-stringop-overread -Wno-psabi -Wno-multichar -Wno-format-zero-length -fno-unwind-tables -fno-asynchronous-unwind-tables -fPIC -pipe -pthread -m64 -msse3 -O2 -fdata-sections -ffunction-sections -fno-math-errno -fno-omit-frame-pointer -gdwarf-4 -g1 -fvisibility=hidden -Wno-narrowing -Wno-class-memaccess -Wno-attributes -Wno-class-memaccess -Wno-subobject-linkage -Wno-invalid-offsetof -Wno-return-type -Wno-deprecated-copy -Wno-invalid-offsetof -Wno-deprecated-copy -Wno-expansion-to-defined -std=gnu++20 -fno-exceptions -fno-rtti -fvisibility-inlines-hidden -c ../../../../../src/3rdparty/chromium/third_party/zlib/google/zip_internal.cc -o obj/third_party/zlib/google/zip/zip_internal.o
../../../../../src/3rdparty/chromium/third_party/zlib/google/zip_internal.cc:180:1: error: â€˜uLongâ€™ does not name a type; did you mean â€˜ulongâ€™?
  180 | uLong ReadZipBuffer(void* opaque, void* /*stream*/, void* buf, uLong size) {
      | ^~~~~
      | ulong
../../../../../src/3rdparty/chromium/third_party/zlib/google/zip_internal.cc:195:1: error: â€˜uLongâ€™ does not name a type; did you mean â€˜ulongâ€™?
  195 | uLong WriteZipBuffer(void* /*opaque*/,
      | ^~~~~
      | ulong
../../../../../src/3rdparty/chromium/third_party/zlib/google/zip_internal.cc: In function â€˜void* zip::internal::PrepareMemoryForUnzipping(const std::string&)â€™:
../../../../../src/3rdparty/chromium/third_party/zlib/google/zip_internal.cc:323:30: error: â€˜ReadZipBufferâ€™ was not declared in this scope
  323 |   zip_functions.zread_file = ReadZipBuffer;
      |                              ^~~~~~~~~~~~~
../../../../../src/3rdparty/chromium/third_party/zlib/google/zip_internal.cc:324:31: error: â€˜WriteZipBufferâ€™ was not declared in this scope
  324 |   zip_functions.zwrite_file = WriteZipBuffer;
      |                               ^~~~~~~~~~~~~~
../../../../../src/3rdparty/chromium/third_party/zlib/google/zip_internal.cc: In function â€˜bool zip::internal::ZipOpenNewFileInZip(zipFile, const std::string&, base::Time, Compression)â€™:
../../../../../src/3rdparty/chromium/third_party/zlib/google/zip_internal.cc:360:9: error: â€˜uLongâ€™ does not name a type; did you mean â€˜ulongâ€™?
  360 |   const uLong LANGUAGE_ENCODING_FLAG = 0x1 << 11;
      |         ^~~~~
      |         ulong
../../../../../src/3rdparty/chromium/third_party/zlib/google/zip_internal.cc:373:17: error: â€˜Z_DEFAULT_COMPRESSIONâ€™ was not declared in this scope
  373 |       /*level=*/Z_DEFAULT_COMPRESSION,
      |                 ^~~~~~~~~~~~~~~~~~~~~
../../../../../src/3rdparty/chromium/third_party/zlib/google/zip_internal.cc:377:20: error: â€˜Z_DEFAULT_STRATEGYâ€™ was not declared in this scope
  377 |       /*strategy=*/Z_DEFAULT_STRATEGY,
      |                    ^~~~~~~~~~~~~~~~~~
../../../../../src/3rdparty/chromium/third_party/zlib/google/zip_internal.cc:381:20: error: â€˜LANGUAGE_ENCODING_FLAGâ€™ was not declared in this scope
  381 |       /*flagBase=*/LANGUAGE_ENCODING_FLAG,
      |